/* ═══════════════════════════════════════════
   Kaohsiung Spot 资料 — 共用景点资料档
   各路线页引用此档取得景点资讯
   ═══════════════════════════════════════════ */

import type { Spot } from "./spot-types";

/** 高雄莲池潭路线景点资料 */
export const kaohsiungLotusPondSpots: Spot[] = [
  {
    id: "lotus-dragon-tiger-pagoda",
    name: "龍虎塔",
    city: "高雄",
    district: "左營區",
    typeTags: ["明信片", "拍照點"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/龍虎塔+蓮池潭+高雄",
    suggestedStayMinutes: 20,
    notes: "蓮池潭代表地標，適合拍照與明信片收集。",
    imagePlaceholder: "/maps/lotus-pond/longhu-tower.jpg",
  },
  {
    id: "lotus-chunqiu-pavilion",
    name: "春秋閣",
    city: "高雄",
    district: "左營區",
    typeTags: ["景點", "步行路線"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/春秋閣+蓮池潭+高雄",
    suggestedStayMinutes: 15,
    notes: "靠近湖岸步道，可接續龍虎塔安排散步。",
    imagePlaceholder: "/maps/lotus-pond/chunqiu-pavilion.jpg",
  },
  {
    id: "lotus-beiji-pavilion",
    name: "元帝廟北極亭",
    city: "高雄",
    district: "左營區",
    typeTags: ["景點", "湖中"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/元帝廟北極亭+蓮池潭+高雄",
    suggestedStayMinutes: 10,
    notes: "湖面視角焦點，可作為路線中段停留點。",
    imagePlaceholder: "/maps/lotus-pond/yuandi-temple.jpg",
  },
  {
    id: "lotus-lakeside-trail",
    name: "蓮池潭環潭步道",
    city: "高雄",
    district: "左營區",
    typeTags: ["種花路線"],
    useTags: ["種花", "散步"],
    tags: ["walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/蓮池潭環潭步道+高雄",
    suggestedStayMinutes: 30,
    notes: "適合 Pikmin Bloom 玩家任務種花與散步。",
    imagePlaceholder: "/maps/lotus-pond/lakeside-trail.jpg",
  },
  {
    id: "lotus-zuoying-temple",
    name: "左營孔廟",
    city: "高雄",
    district: "左營區",
    typeTags: ["文化景點"],
    useTags: ["散步", "文化"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/左營孔廟+蓮池潭+高雄",
    suggestedStayMinutes: 30,
    notes: "蓮池潭北側文化景點，適合半日遊延伸。",
    imagePlaceholder: "/maps/lotus-pond/zuoying-temple.jpg",
  },
  {
    id: "lotus-lotus-pond",
    name: "蓮池潭",
    city: "高雄",
    district: "左營區",
    typeTags: ["湖泊"],
    useTags: ["散步", "親子"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/蓮池潭+高雄",
    suggestedStayMinutes: 20,
    notes: "湖區自然景觀，適合散步與親子路線。",
    imagePlaceholder: "/maps/lotus-pond/lotus-pond.jpg",
  },
  {
    id: "lotus-children-park",
    name: "蓮池潭兒童公園",
    city: "高雄",
    district: "左營區",
    typeTags: ["公園", "休息"],
    useTags: ["親子", "休息"],
    tags: ["walk"],
    googleMapsUrl: "https://www.google.com/maps/search/蓮池潭兒童公園+高雄",
    suggestedStayMinutes: 20,
    notes: "兒童遊戲場所，適合放風。",
    imagePlaceholder: "/maps/lotus-pond/children-park.jpg",
  },
  {
    id: "lotus-zhouzai-wetland",
    name: "洲仔濕地",
    city: "高雄",
    district: "左營區",
    typeTags: ["自然", "公園"],
    useTags: ["生態教育", "散步"],
    tags: ["walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/洲仔濕地+蓮池潭+高雄",
    suggestedStayMinutes: 25,
    notes: "自然景觀，適合生態教育。",
    imagePlaceholder: "/maps/lotus-pond/zhouzai-wetland.jpg",
  },
];

/** 高雄駁二藝術特區路線景點資料 (A-H 點位) */
export const kaohsiungPier2Spots: Spot[] = [
  {
    id: "pier2-A",
    name: "高雄流行音樂中心",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["音樂廳", "地標", "港邊"],
    useTags: ["明信片收集", "拍照", "散步"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/高雄流行音樂中心+駁二",
    suggestedStayMinutes: 30,
    notes: "高雄港邊地標建築，鯨魚造型展演空間，日夜景各有風情。",
    imagePlaceholder: "/maps/pier-2/a.png",
  },
  {
    id: "pier2-B",
    name: "駁二大勇區",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["文創園區", "倉庫群"],
    useTags: ["明信片收集", "散步", "逛街"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/駁二大勇區",
    suggestedStayMinutes: 40,
    notes: "駁二主展區，倉庫改建為藝廊、商店與餐廳，假日市集熱鬧。",
    imagePlaceholder: "/maps/pier-2/b.png",
  },
  {
    id: "pier2-C",
    name: "大港橋",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["景觀橋", "港邊"],
    useTags: ["拍照", "散步"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/大港橋+高雄",
    suggestedStayMinutes: 15,
    notes: "可旋轉開啟的景觀橋，連結駁二與棧貳庫，日落時分景色絕佳。",
    imagePlaceholder: "/maps/pier-2/c.png",
  },
  {
    id: "pier2-D",
    name: "駁二大義區",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["文創園區", "倉庫群"],
    useTags: ["散步", "逛街", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/駁二大義區",
    suggestedStayMinutes: 30,
    notes: "輕軌大義站旁，倉庫群內有誠品書店、展演空間與特色餐廳。",
    imagePlaceholder: "/maps/pier-2/d.png",
  },
  {
    id: "pier2-E",
    name: "駁二蓬萊倉庫群",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["歷史建築", "倉庫群"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/駁二蓬萊倉庫群",
    suggestedStayMinutes: 25,
    notes: "歷史倉庫群改建的文創聚落，鄰近哈瑪星與輕軌蓬萊站。",
    imagePlaceholder: "/maps/pier-2/e.png",
  },
  {
    id: "pier2-F",
    name: "哈瑪星鐵道園區",
    city: "高雄",
    district: "鼓山區",
    typeTags: ["鐵道文化", "公園", "歷史"],
    useTags: ["散步", "拍照", "親子"],
    tags: ["walk", "postcard", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/哈瑪星鐵道文化園區",
    suggestedStayMinutes: 30,
    notes: "舊鐵道與草地廣場，適合散步、野餐與鐵道攝影，駁二路線終點延伸。",
    imagePlaceholder: "/maps/pier-2/f.png",
  },
  {
    id: "pier2-G",
    name: "舊打狗驛故事館",
    city: "高雄",
    district: "鼓山區",
    typeTags: ["博物館", "鐵道文化", "歷史"],
    useTags: ["散步", "文化學習"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/舊打狗驛故事館",
    suggestedStayMinutes: 20,
    notes: "原高雄港站改建的鐵道博物館，展示老火車與港站歷史。",
    imagePlaceholder: "/maps/pier-2/g.png",
  },
  {
    id: "pier2-H",
    name: "棧貳庫KW2",
    city: "高雄",
    district: "鼓山區",
    typeTags: ["文創商場", "港邊", "美食"],
    useTags: ["逛街", "用餐", "拍照"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/棧貳庫+高雄",
    suggestedStayMinutes: 40,
    notes: "港邊百年倉庫改建的美食文創商場，可搭旋轉景觀橋往返駁二。",
    imagePlaceholder: "/maps/pier-2/h.png",
  },
];

/** 根据 id 从指定景点列表中查找 */
/** 高雄旗津路線景點資料 (A-H 點位) */
export const kaohsiungQijinSpots: Spot[] = [
  {
    id: "qijin-A",
    name: "旗津渡輪站",
    city: "高雄",
    district: "旗津區",
    typeTags: ["渡輪站", "港邊"],
    useTags: ["拍照", "散步"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/旗津渡輪站+高雄",
    suggestedStayMinutes: 15,
    notes: "往返旗津與鼓山的交通樞紐，出站即是旗津老街入口，海風與渡輪景色相伴。",
    imagePlaceholder: "/maps/qijin/a.png",
  },
  {
    id: "qijin-B",
    name: "旗津天后宮",
    city: "高雄",
    district: "旗津區",
    typeTags: ["廟宇", "歷史建築", "文化"],
    useTags: ["散步", "文化學習"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/旗津天后宮+高雄",
    suggestedStayMinutes: 20,
    notes: "旗津信仰中心，三百餘年歷史的媽祖廟，廟宇裝飾精緻，香火鼎盛。",
    imagePlaceholder: "/maps/qijin/b.png",
  },
  {
    id: "qijin-C",
    name: "旗津老街",
    city: "高雄",
    district: "旗津區",
    typeTags: ["老街", "美食", "商圈"],
    useTags: ["用餐", "逛街", "散步"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/旗津老街+高雄",
    suggestedStayMinutes: 30,
    notes: "旗津最熱鬧的市街，烤小卷、海產與在地小吃集中地，假日人潮絡繹不絕。",
    imagePlaceholder: "/maps/qijin/c.png",
  },
  {
    id: "qijin-D",
    name: "旗津燈塔",
    city: "高雄",
    district: "旗津區",
    typeTags: ["燈塔", "歷史建築", "海景"],
    useTags: ["明信片收集", "拍照", "散步"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/旗津燈塔+高雄",
    suggestedStayMinutes: 25,
    notes: "白色八角形燈塔，建於清末，俯瞰高雄港入口，是旗津經典地標與明信片焦點。",
    imagePlaceholder: "/maps/qijin/d.png",
  },
  {
    id: "qijin-E",
    name: "旗津星空隧道",
    city: "高雄",
    district: "旗津區",
    typeTags: ["隧道", "夜景", "藝術"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/旗津星空隧道+高雄",
    suggestedStayMinutes: 15,
    notes: "廢棄軍事隧道改建而成的星光步道，壁面彩繪螢光星空，白天與夜晚各有不同氛圍。",
    imagePlaceholder: "/maps/qijin/e.png",
  },
  {
    id: "qijin-F",
    name: "旗後砲台",
    city: "高雄",
    district: "旗津區",
    typeTags: ["砲台", "歷史建築", "古蹟"],
    useTags: ["散步", "文化學習", "拍照"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/旗後砲台+高雄",
    suggestedStayMinutes: 25,
    notes: "清末海防砲台遺址，城牆與砲座保存完整，居高臨下可眺望高雄港與台灣海峽。",
    imagePlaceholder: "/maps/qijin/f.png",
  },
  {
    id: "qijin-G",
    name: "旗津海岸景觀",
    city: "高雄",
    district: "旗津區",
    typeTags: ["海灘", "海岸", "自然"],
    useTags: ["散步", "拍照"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/旗津海岸公園+高雄",
    suggestedStayMinutes: 25,
    notes: "旗津南側的長長沙灘與海岸步道，適合看海、散步、吹海風。",
    imagePlaceholder: "/maps/qijin/g.png",
  },
  {
    id: "qijin-H",
    name: "旗津彩虹教堂",
    city: "高雄",
    district: "旗津區",
    typeTags: ["教堂", "拍照點", "地標"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/旗津彩虹教堂+高雄",
    suggestedStayMinutes: 20,
    notes: "以彩虹色幾何拱門為造型的婚紗與打卡熱點，搭配海天一色背景，畫面感強烈。",
    imagePlaceholder: "/maps/qijin/h.png",
  },
];
export function getSpotById(
  spots: Spot[],
  id: string,
): Spot | undefined {
  return spots.find((s) => s.id === id);
}

