/* ═══════════════════════════════════════════
   Kaohsiung Spot 资料 — 共用景点资料档
   各路线页引用此档取得景点资讯
   ═══════════════════════════════════════════ */

import type { Spot } from "./spot-types";

/** 高雄莲池潭路线景点资料 */
export const kaohsiungLotusPondSpots: Spot[] = [
  {
    id: "lotus-dragon-tiger-pagoda",
    name: "龍虎塔",
    city: "高雄",
    district: "左營區",
    typeTags: ["明信片", "拍照點"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/龍虎塔+蓮池潭+高雄",
    suggestedStayMinutes: 20,
    notes: "蓮池潭代表地標，適合拍照與明信片收集。",
    imagePlaceholder: "/maps/lotus-pond/longhu-tower.jpg",
  },
  {
    id: "lotus-chunqiu-pavilion",
    name: "春秋閣",
    city: "高雄",
    district: "左營區",
    typeTags: ["景點", "步行路線"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/春秋閣+蓮池潭+高雄",
    suggestedStayMinutes: 15,
    notes: "靠近湖岸步道，可接續龍虎塔安排散步。",
    imagePlaceholder: "/maps/lotus-pond/chunqiu-pavilion.jpg",
  },
  {
    id: "lotus-beiji-pavilion",
    name: "元帝廟北極亭",
    city: "高雄",
    district: "左營區",
    typeTags: ["景點", "湖中"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/元帝廟北極亭+蓮池潭+高雄",
    suggestedStayMinutes: 10,
    notes: "湖面視角焦點，可作為路線中段停留點。",
    imagePlaceholder: "/maps/lotus-pond/yuandi-temple.jpg",
  },
  {
    id: "lotus-lakeside-trail",
    name: "蓮池潭環潭步道",
    city: "高雄",
    district: "左營區",
    typeTags: ["種花路線"],
    useTags: ["種花", "散步"],
    tags: ["walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/蓮池潭環潭步道+高雄",
    suggestedStayMinutes: 30,
    notes: "適合 Pikmin Bloom 玩家任務種花與散步。",
    imagePlaceholder: "/maps/lotus-pond/lakeside-trail.jpg",
  },
  {
    id: "lotus-zuoying-temple",
    name: "左營孔廟",
    city: "高雄",
    district: "左營區",
    typeTags: ["文化景點"],
    useTags: ["散步", "文化"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/左營孔廟+蓮池潭+高雄",
    suggestedStayMinutes: 30,
    notes: "蓮池潭北側文化景點，適合半日遊延伸。",
    imagePlaceholder: "/maps/lotus-pond/zuoying-temple.jpg",
  },
  {
    id: "lotus-lotus-pond",
    name: "蓮池潭",
    city: "高雄",
    district: "左營區",
    typeTags: ["湖泊"],
    useTags: ["散步", "親子"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/蓮池潭+高雄",
    suggestedStayMinutes: 20,
    notes: "湖區自然景觀，適合散步與親子路線。",
    imagePlaceholder: "/maps/lotus-pond/lotus-pond.jpg",
  },
  {
    id: "lotus-children-park",
    name: "蓮池潭兒童公園",
    city: "高雄",
    district: "左營區",
    typeTags: ["公園", "休息"],
    useTags: ["親子", "休息"],
    tags: ["walk"],
    googleMapsUrl: "https://www.google.com/maps/search/蓮池潭兒童公園+高雄",
    suggestedStayMinutes: 20,
    notes: "兒童遊戲場所，適合放風。",
    imagePlaceholder: "/maps/lotus-pond/children-park.jpg",
  },
  {
    id: "lotus-zhouzai-wetland",
    name: "洲仔濕地",
    city: "高雄",
    district: "左營區",
    typeTags: ["自然", "公園"],
    useTags: ["生態教育", "散步"],
    tags: ["walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/洲仔濕地+蓮池潭+高雄",
    suggestedStayMinutes: 25,
    notes: "自然景觀，適合生態教育。",
    imagePlaceholder: "/maps/lotus-pond/zhouzai-wetland.jpg",
  },
];

/** 高雄駁二藝術特區路線景點資料 (A-H 點位) */
export const kaohsiungPier2Spots: Spot[] = [
  {
    id: "pier2-A",
    name: "高雄流行音樂中心",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["音樂廳", "地標", "港邊"],
    useTags: ["明信片收集", "拍照", "散步"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/高雄流行音樂中心+駁二",
    suggestedStayMinutes: 30,
    notes: "高雄港邊地標建築，鯨魚造型展演空間，日夜景各有風情。",
    imagePlaceholder: "/maps/pier-2/a.png",
  },
  {
    id: "pier2-B",
    name: "駁二大勇區",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["文創園區", "倉庫群"],
    useTags: ["明信片收集", "散步", "逛街"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/駁二大勇區",
    suggestedStayMinutes: 40,
    notes: "駁二主展區，倉庫改建為藝廊、商店與餐廳，假日市集熱鬧。",
    imagePlaceholder: "/maps/pier-2/b.png",
  },
  {
    id: "pier2-C",
    name: "大港橋",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["景觀橋", "港邊"],
    useTags: ["拍照", "散步"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/大港橋+高雄",
    suggestedStayMinutes: 15,
    notes: "可旋轉開啟的景觀橋，連結駁二與棧貳庫，日落時分景色絕佳。",
    imagePlaceholder: "/maps/pier-2/c.png",
  },
  {
    id: "pier2-D",
    name: "駁二大義區",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["文創園區", "倉庫群"],
    useTags: ["散步", "逛街", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/駁二大義區",
    suggestedStayMinutes: 30,
    notes: "輕軌大義站旁，倉庫群內有誠品書店、展演空間與特色餐廳。",
    imagePlaceholder: "/maps/pier-2/d.png",
  },
  {
    id: "pier2-E",
    name: "駁二蓬萊倉庫群",
    city: "高雄",
    district: "鹽埕區",
    typeTags: ["歷史建築", "倉庫群"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/駁二蓬萊倉庫群",
    suggestedStayMinutes: 25,
    notes: "歷史倉庫群改建的文創聚落，鄰近哈瑪星與輕軌蓬萊站。",
    imagePlaceholder: "/maps/pier-2/e.png",
  },
  {
    id: "pier2-F",
    name: "哈瑪星鐵道園區",
    city: "高雄",
    district: "鼓山區",
    typeTags: ["鐵道文化", "公園", "歷史"],
    useTags: ["散步", "拍照", "親子"],
    tags: ["walk", "postcard", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/哈瑪星鐵道文化園區",
    suggestedStayMinutes: 30,
    notes: "舊鐵道與草地廣場，適合散步、野餐與鐵道攝影，駁二路線終點延伸。",
    imagePlaceholder: "/maps/pier-2/f.png",
  },
  {
    id: "pier2-G",
    name: "舊打狗驛故事館",
    city: "高雄",
    district: "鼓山區",
    typeTags: ["博物館", "鐵道文化", "歷史"],
    useTags: ["散步", "文化學習"],
    tags: ["walk", "heritage", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/舊打狗驛故事館",
    suggestedStayMinutes: 20,
    notes: "原高雄港站改建的鐵道博物館，展示老火車與港站歷史。",
    imagePlaceholder: "/maps/pier-2/g.png",
  },
  {
    id: "pier2-H",
    name: "棧貳庫KW2",
    city: "高雄",
    district: "鼓山區",
    typeTags: ["文創商場", "港邊", "美食"],
    useTags: ["逛街", "用餐", "拍照"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/棧貳庫+高雄",
    suggestedStayMinutes: 40,
    notes: "港邊百年倉庫改建的美食文創商場，可搭旋轉景觀橋往返駁二。",
    imagePlaceholder: "/maps/pier-2/h.png",
  },
];

/** 根据 id 从指定景点列表中查找 */
export function getSpotById(
  spots: Spot[],
  id: string,
): Spot | undefined {
  return spots.find((s) => s.id === id);
}

