/* ═══════════════════════════════════════════
   Tainan Spot 资料 — 共用景点资料档
   各路线页引用此档取得景点资讯
   ═══════════════════════════════════════════ */

import type { Spot } from "./spot-types";

/* ─── 安平古堡路線 (A-H, 8 點位) ─── */
export const tainanAnpingSpots: Spot[] = [
  {
    id: "tainan-anping-A",
    name: "安平古堡",
    city: "臺南",
    district: "安平區",
    typeTags: ["古蹟", "歷史建築"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/安平古堡+臺南",
    suggestedStayMinutes: 30,
    notes: "臺灣最古老的要塞城堡之一，紅磚城牆與瞭望臺是安平經典地標。",
    imagePlaceholder: "/maps/anping-old-fort/A.png",
  },
  {
    id: "tainan-anping-B",
    name: "安平老街",
    city: "臺南",
    district: "安平區",
    typeTags: ["老街", "美食"],
    useTags: ["散步", "美食"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/安平老街+臺南",
    suggestedStayMinutes: 30,
    notes: "安平最熱鬧的傳統街區，沿途有小吃、伴手禮與老屋巷弄。",
    imagePlaceholder: "/maps/anping-old-fort/B.png",
  },
  {
    id: "tainan-anping-C",
    name: "英商德記洋行",
    city: "臺南",
    district: "安平區",
    typeTags: ["歷史建築", "洋行"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/德記洋行+安平+臺南",
    suggestedStayMinutes: 20,
    notes: "安平港區三大洋行之一，白色拱廊建築別具西洋風情。",
    imagePlaceholder: "/maps/anping-old-fort/C.png",
  },
  {
    id: "tainan-anping-D",
    name: "安平樹屋",
    city: "臺南",
    district: "安平區",
    typeTags: ["自然", "歷史建築"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/安平樹屋+臺南",
    suggestedStayMinutes: 25,
    notes: "老榕樹根盤據倉庫廢墟形成「樹屋共生」奇景，極具明信片感。",
    imagePlaceholder: "/maps/anping-old-fort/D.png",
  },
  {
    id: "tainan-anping-E",
    name: "東興洋行",
    city: "臺南",
    district: "安平區",
    typeTags: ["歷史建築", "洋行"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/東興洋行+安平+臺南",
    suggestedStayMinutes: 15,
    notes: "安平港區洋行建築群之一，磚造拱廊建築充滿懷舊氛圍。",
    imagePlaceholder: "/maps/anping-old-fort/E.png",
  },
  {
    id: "tainan-anping-F",
    name: "盧經堂古厝",
    city: "臺南",
    district: "安平區",
    typeTags: ["古蹟", "傳統建築"],
    useTags: ["散步", "文化"],
    tags: ["walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/盧經堂古厝+安平+臺南",
    suggestedStayMinutes: 15,
    notes: "安平經典傳統合院建築，展現清代富商宅邸格局。",
    imagePlaceholder: "/maps/anping-old-fort/F.png",
  },
  {
    id: "tainan-anping-G",
    name: "安平小砲臺",
    city: "臺南",
    district: "安平區",
    typeTags: ["古蹟", "軍事遺址"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/安平小砲臺+臺南",
    suggestedStayMinutes: 10,
    notes: "清代安平港防禦砲臺遺址，港邊歷史景點。",
    imagePlaceholder: "/maps/anping-old-fort/G.jpg",
  },
  {
    id: "tainan-anping-H",
    name: "開台天后宮",
    city: "臺南",
    district: "安平區",
    typeTags: ["廟宇", "文化景點"],
    useTags: ["文化", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/開台天后宮+安平+臺南",
    suggestedStayMinutes: 15,
    notes: "安平信仰中心，媽祖廟建築細節豐富，適合拍照。",
    imagePlaceholder: "/maps/anping-old-fort/H.png",
  },
];

/* ─── 赤崁樓・府城古蹟路線 (A-F, 6 點位) ─── */
export const tainanChihkanSpots: Spot[] = [
  {
    id: "tainan-chihkan-A",
    name: "赤崁樓",
    city: "臺南",
    district: "中西區",
    typeTags: ["古蹟", "歷史建築"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/赤崁樓+臺南",
    suggestedStayMinutes: 30,
    notes: "府城核心古蹟，荷蘭人所建，海石承臺與中式閣樓並存。",
    imagePlaceholder: "/maps/chihkan-old-town/A.png",
  },
  {
    id: "tainan-chihkan-B",
    name: "神農街",
    city: "臺南",
    district: "中西區",
    typeTags: ["老街", "文創"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/神農街+臺南",
    suggestedStayMinutes: 25,
    notes: "臺南保存最完整的老街之一，老屋與文創小店交錯。",
    imagePlaceholder: "/maps/chihkan-old-town/B.png",
  },
  {
    id: "tainan-chihkan-C",
    name: "河樂廣場",
    city: "臺南",
    district: "中西區",
    typeTags: ["廣場", "親水"],
    useTags: ["休息", "散步"],
    tags: ["walk"],
    googleMapsUrl: "https://www.google.com/maps/search/河樂廣場+臺南",
    suggestedStayMinutes: 20,
    notes: "舊中國城改建的親水廣場，傍晚適合散步休息。",
    imagePlaceholder: "/maps/chihkan-old-town/C.png",
  },
  {
    id: "tainan-chihkan-D",
    name: "海安路藝術街",
    city: "臺南",
    district: "中西區",
    typeTags: ["藝術", "街道"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/海安路藝術街+臺南",
    suggestedStayMinutes: 20,
    notes: "海安路兩側大型壁畫與藝術裝置，夜間燈光氛圍尤佳。",
    imagePlaceholder: "/maps/chihkan-old-town/D.png",
  },
  {
    id: "tainan-chihkan-E",
    name: "蝸牛巷",
    city: "臺南",
    district: "中西區",
    typeTags: ["巷弄", "文創"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/蝸牛巷+臺南",
    suggestedStayMinutes: 15,
    notes: "以蝸牛為主題的藝術巷弄，適合散步尋寶與拍照。",
    imagePlaceholder: "/maps/chihkan-old-town/E.png",
  },
  {
    id: "tainan-chihkan-F",
    name: "文鼎留聲博物館",
    city: "臺南",
    district: "中西區",
    typeTags: ["博物館", "文化"],
    useTags: ["文化", "明信片收集"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/文鼎留聲博物館+臺南",
    suggestedStayMinutes: 30,
    notes: "以留聲機與聲音歷史為主題的博物館，收藏豐富。",
    imagePlaceholder: "/maps/chihkan-old-town/F.png",
  },
];

/* ─── 孔廟文化路線 (A-H, 8 點位) ─── */
export const tainanConfuciusSpots: Spot[] = [
  {
    id: "tainan-confucius-A",
    name: "臺灣文學館",
    city: "臺南",
    district: "中西區",
    typeTags: ["博物館", "文學"],
    useTags: ["明信片收集", "文化"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/國立臺灣文學館+臺南",
    suggestedStayMinutes: 40,
    notes: "日治時期臺南州廳建築改建，收藏臺灣文學史料。",
    imagePlaceholder: "/maps/tainan-confucius-temple/A.png",
  },
  {
    id: "tainan-confucius-B",
    name: "臺南市美術館",
    city: "臺南",
    district: "中西區",
    typeTags: ["博物館", "藝術"],
    useTags: ["明信片收集", "文化"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/臺南市美術館+臺南",
    suggestedStayMinutes: 40,
    notes: "現代化藝術展覽空間，建築本身即是拍照亮點。",
    imagePlaceholder: "/maps/tainan-confucius-temple/B.png",
  },
  {
    id: "tainan-confucius-C",
    name: "臺南孔廟",
    city: "臺南",
    district: "中西區",
    typeTags: ["古蹟", "廟宇"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/臺南孔廟+臺南",
    suggestedStayMinutes: 30,
    notes: "臺灣第一座孔子廟，大成殿與泮池是經典文化地標。",
    imagePlaceholder: "/maps/tainan-confucius-temple/C.png",
  },
  {
    id: "tainan-confucius-D",
    name: "愛國婦人館",
    city: "臺南",
    district: "中西區",
    typeTags: ["歷史建築", "文化"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/愛國婦人館+臺南",
    suggestedStayMinutes: 15,
    notes: "日治時期建築，紅磚與和洋風格融合。",
    imagePlaceholder: "/maps/tainan-confucius-temple/D.png",
  },
  {
    id: "tainan-confucius-E",
    name: "司法博物館",
    city: "臺南",
    district: "中西區",
    typeTags: ["博物館", "歷史建築"],
    useTags: ["文化", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/司法博物館+臺南",
    suggestedStayMinutes: 25,
    notes: "日治時期臺南地方法院，巴洛克式建築宏偉壯觀。",
    imagePlaceholder: "/maps/tainan-confucius-temple/E.png",
  },
  {
    id: "tainan-confucius-F",
    name: "假日花市",
    city: "臺南",
    district: "中西區",
    typeTags: ["市集", "花卉"],
    useTags: ["散步", "親子"],
    tags: ["walk"],
    googleMapsUrl: "https://www.google.com/maps/search/臺南假日花市",
    suggestedStayMinutes: 20,
    notes: "南門路旁的假日花卉市集，適合散步與選購盆栽。",
    imagePlaceholder: "/maps/tainan-confucius-temple/F.png",
  },
  {
    id: "tainan-confucius-G",
    name: "南門公園",
    city: "臺南",
    district: "中西區",
    typeTags: ["公園", "歷史"],
    useTags: ["散步", "休息"],
    tags: ["walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/南門公園+臺南",
    suggestedStayMinutes: 20,
    notes: "擁有南門城遺跡的綠地公園，適合種花與休息。",
    imagePlaceholder: "/maps/tainan-confucius-temple/G.png",
  },
  {
    id: "tainan-confucius-H",
    name: "國家美術館",
    city: "臺南",
    district: "中西區",
    typeTags: ["博物館", "藝術"],
    useTags: ["文化", "明信片收集"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/臺南國家美術館",
    suggestedStayMinutes: 30,
    notes: "國家級美術館，當代與傳統藝術展覽空間。",
    imagePlaceholder: "/maps/tainan-confucius-temple/H.png",
  },
];

/* ─── 漁光島海景路線 (A-F, 6 點位) ─── */
export const tainanYuguangSpots: Spot[] = [
  {
    id: "tainan-yuguang-A",
    name: "林默娘公園",
    city: "臺南",
    district: "安平區",
    typeTags: ["公園", "雕像"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/林默娘公園+臺南",
    suggestedStayMinutes: 20,
    notes: "港邊媽祖雕像公園，視野開闊適合散步。",
    imagePlaceholder: "/maps/yuguang-island/A.png",
  },
  {
    id: "tainan-yuguang-B",
    name: "定情碼頭德陽艦園區",
    city: "臺南",
    district: "安平區",
    typeTags: ["軍事", "博物館"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/德陽艦園區+臺南",
    suggestedStayMinutes: 30,
    notes: "退役海軍驅逐艦改造的博物館園區，艦上視野絕佳。",
    imagePlaceholder: "/maps/yuguang-island/B.png",
  },
  {
    id: "tainan-yuguang-C",
    name: "億載金城",
    city: "臺南",
    district: "安平區",
    typeTags: ["古蹟", "軍事遺址"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/億載金城+臺南",
    suggestedStayMinutes: 25,
    notes: "清代西式砲臺要塞，護城河與紅磚城門極具歷史氛圍。",
    imagePlaceholder: "/maps/yuguang-island/C.png",
  },
  {
    id: "tainan-yuguang-D",
    name: "漁光島",
    city: "臺南",
    district: "安平區",
    typeTags: ["海灘", "自然"],
    useTags: ["明信片收集", "散步"],
    tags: ["postcard", "walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/漁光島+臺南",
    suggestedStayMinutes: 30,
    notes: "安平港外的小島沙灘，夕陽景致極美。",
    imagePlaceholder: "/maps/yuguang-island/D.png",
  },
  {
    id: "tainan-yuguang-E",
    name: "虱目魚主題館",
    city: "臺南",
    district: "安平區",
    typeTags: ["美食", "文化"],
    useTags: ["美食", "文化"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/虱目魚主題館+臺南",
    suggestedStayMinutes: 20,
    notes: "以虱目魚為主題的展售館，了解臺南在地魚產文化。",
    imagePlaceholder: "/maps/yuguang-island/E.png",
  },
  {
    id: "tainan-yuguang-F",
    name: "巨人耳機防波堤",
    city: "臺南",
    district: "安平區",
    typeTags: ["藝術", "海景"],
    useTags: ["拍照", "散步"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/漁光島巨人耳機防波堤+臺南",
    suggestedStayMinutes: 15,
    notes: "漁光島沙灘旁的彩色防波堤，造型宛如巨人耳機。",
    imagePlaceholder: "/maps/yuguang-island/F.png",
  },
];

/* ─── 奇美博物館・都會公園路線 (A-H, 8 點位) ─── */
export const tainanChimeiSpots: Spot[] = [
  {
    id: "tainan-chimei-A",
    name: "奇美博物館",
    city: "臺南",
    district: "仁德區",
    typeTags: ["博物館", "藝術"],
    useTags: ["明信片收集", "拍照"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/奇美博物館+臺南",
    suggestedStayMinutes: 60,
    notes: "臺南最具代表性的博物館，歐式建築與豐富典藏。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/A.png",
  },
  {
    id: "tainan-chimei-B",
    name: "繆思廣場",
    city: "臺南",
    district: "仁德區",
    typeTags: ["廣場", "藝術"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/奇美博物館繆思廣場+臺南",
    suggestedStayMinutes: 15,
    notes: "博物館正面廣場，希臘神話雕塑環繞。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/B.png",
  },
  {
    id: "tainan-chimei-C",
    name: "風動草原",
    city: "臺南",
    district: "仁德區",
    typeTags: ["公園", "草地"],
    useTags: ["散步", "種花"],
    tags: ["walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/奇美博物館風動草原+臺南",
    suggestedStayMinutes: 20,
    notes: "博物館旁大草原，適合種花與野餐。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/C.png",
  },
  {
    id: "tainan-chimei-D",
    name: "臺南都會公園",
    city: "臺南",
    district: "仁德區",
    typeTags: ["公園", "湖景"],
    useTags: ["散步", "種花"],
    tags: ["walk", "pikmin"],
    googleMapsUrl: "https://www.google.com/maps/search/臺南都會公園+仁德",
    suggestedStayMinutes: 30,
    notes: "廣闊的都會公園，湖景步道與綠地兼具。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/D.png",
  },
  {
    id: "tainan-chimei-E",
    name: "阿波羅噴泉廣場",
    city: "臺南",
    district: "仁德區",
    typeTags: ["廣場", "藝術"],
    useTags: ["拍照", "散步"],
    tags: ["postcard", "walk"],
    googleMapsUrl: "https://www.google.com/maps/search/奇美博物館阿波羅噴泉+臺南",
    suggestedStayMinutes: 15,
    notes: "阿波羅太陽神噴泉雕塑，歐式庭園風格。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/E.png",
  },
  {
    id: "tainan-chimei-F",
    name: "觀水平臺",
    city: "臺南",
    district: "仁德區",
    typeTags: ["觀景", "湖景"],
    useTags: ["拍照", "休息"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/奇美博物館觀水平臺+臺南",
    suggestedStayMinutes: 10,
    notes: "湖畔觀景平臺，欣賞湖景與博物館倒影。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/F.png",
  },
  {
    id: "tainan-chimei-G",
    name: "奧林帕斯橋",
    city: "臺南",
    district: "仁德區",
    typeTags: ["橋樑", "藝術"],
    useTags: ["散步", "拍照"],
    tags: ["walk", "postcard"],
    googleMapsUrl: "https://www.google.com/maps/search/奇美博物館奧林帕斯橋+臺南",
    suggestedStayMinutes: 10,
    notes: "連接博物館與都會公園的景觀橋，眾神雕塑裝飾。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/G.png",
  },
  {
    id: "tainan-chimei-H",
    name: "十鼓文創園區",
    city: "臺南",
    district: "仁德區",
    typeTags: ["文創", "表演"],
    useTags: ["文化", "明信片收集"],
    tags: ["postcard", "walk", "heritage"],
    googleMapsUrl: "https://www.google.com/maps/search/十鼓文創園區+臺南",
    suggestedStayMinutes: 45,
    notes: "由舊糖廠改建的擊樂表演文創園區，工業遺產與藝術融合。",
    imagePlaceholder: "/maps/chimei-metropolitan-park/H.png",
  },
];
